-- Multi-service orders, idempotent checkout, points ledger and safe cancellation.
-- Run after 001_schema.sql and 002_secure_loyalty.sql.

-- ---------------------------------------------------------------------------
-- Order header and line items
-- ---------------------------------------------------------------------------
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  receipt_number bigint generated by default as identity unique,
  customer_id uuid not null references public.profiles(id),
  worker_id uuid not null references public.profiles(id),
  payment_method text not null check (payment_method in ('cash', 'card', 'transfer', 'points')),
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  points_added integer not null default 0 check (points_added >= 0),
  points_redeemed integer not null default 0 check (points_redeemed >= 0),
  status text not null default 'completed' check (status in ('completed', 'cancelled')),
  client_request_id uuid not null unique,
  cancelled_at timestamptz,
  cancelled_by uuid references public.profiles(id),
  cancellation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (status = 'completed' and cancelled_at is null and cancelled_by is null)
    or
    (status = 'cancelled' and cancelled_at is not null and cancelled_by is not null and coalesce(length(trim(cancellation_reason)), 0) >= 3)
  )
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete restrict,
  service_id uuid not null references public.services(id),
  quantity integer not null default 1 check (quantity between 1 and 20),
  base_unit_price numeric(12,2) not null check (base_unit_price >= 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  points_reward integer not null default 0 check (points_reward >= 0),
  line_total numeric(12,2) generated always as (unit_price * quantity) stored,
  created_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_customer_idx on public.orders(customer_id, created_at desc);
create index if not exists orders_worker_idx on public.orders(worker_id, created_at desc);
create index if not exists orders_status_idx on public.orders(status, created_at desc);
create index if not exists order_items_order_idx on public.order_items(order_id);

-- Every balance mutation is recorded. Historical imports can have a null
-- balance_after because their original intermediate balances are unknown.
create table if not exists public.points_ledger (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.profiles(id),
  order_id uuid references public.orders(id),
  actor_id uuid references public.profiles(id),
  delta integer not null check (delta <> 0),
  balance_after integer check (balance_after >= 0),
  reason text not null check (reason in ('earned', 'redeemed', 'reversal', 'admin_adjustment', 'legacy_import')),
  note text,
  created_at timestamptz not null default now()
);

create index if not exists points_ledger_customer_idx on public.points_ledger(customer_id, created_at desc);
create index if not exists points_ledger_order_idx on public.points_ledger(order_id);

alter table public.loyalty_settings
  add column if not exists reward_service_id uuid references public.services(id);

update public.loyalty_settings settings
set reward_service_id = (
  select id from public.services
  where is_active = true and price > 0
  order by sort_order, created_at
  limit 1
)
where settings.id = 1 and settings.reward_service_id is null;

-- ---------------------------------------------------------------------------
-- Preserve old single-service transactions in the new reporting model.
-- ---------------------------------------------------------------------------
insert into public.orders (
  id, customer_id, worker_id, payment_method, subtotal, total_amount,
  points_added, points_redeemed, status, client_request_id, created_at, updated_at
)
select
  tx.id, tx.customer_id, tx.worker_id, tx.payment_method, tx.amount, tx.amount,
  tx.points_added, 0, 'completed', tx.id, tx.created_at, tx.created_at
from public.transactions tx
on conflict (id) do nothing;

insert into public.order_items (
  order_id, service_id, quantity, base_unit_price, unit_price, points_reward, created_at
)
select
  tx.id, tx.service_id, 1, service.price, tx.amount, tx.points_added, tx.created_at
from public.transactions tx
join public.services service on service.id = tx.service_id
where not exists (select 1 from public.order_items item where item.order_id = tx.id);

insert into public.points_ledger (customer_id, order_id, actor_id, delta, balance_after, reason, note, created_at)
select tx.customer_id, tx.id, tx.worker_id, tx.points_added, null, 'legacy_import', 'Imported from transactions', tx.created_at
from public.transactions tx
where tx.points_added <> 0
  and not exists (
    select 1 from public.points_ledger ledger
    where ledger.order_id = tx.id and ledger.reason = 'legacy_import'
  );

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.points_ledger enable row level security;

drop policy if exists "orders read" on public.orders;
create policy "orders read" on public.orders for select
  using (customer_id = auth.uid() or public.is_staff());

drop policy if exists "order items read" on public.order_items;
create policy "order items read" on public.order_items for select
  using (
    exists (
      select 1 from public.orders order_row
      where order_row.id = order_id
        and (order_row.customer_id = auth.uid() or public.is_staff())
    )
  );

drop policy if exists "points ledger read" on public.points_ledger;
create policy "points ledger read" on public.points_ledger for select
  using (customer_id = auth.uid() or public.is_staff());

-- No insert/update/delete policies are intentionally created. Writes are only
-- possible through the security-definer functions below.

-- ---------------------------------------------------------------------------
-- Staff customer lookup (safe preview before charging)
-- ---------------------------------------------------------------------------
create or replace function public.resolve_customer(customer_reference text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  customer public.profiles%rowtype;
  reference text;
begin
  if not public.is_staff() then
    raise exception 'STAFF_ACCESS_REQUIRED' using errcode = '42501';
  end if;

  reference := regexp_replace(trim(coalesce(customer_reference, '')), '^rio-customer:v1:', '', 'i');

  if reference ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    select * into customer from public.profiles
    where id = reference::uuid and role = 'customer';
  else
    select * into customer from public.profiles
    where phone = public.normalize_phone(reference) and role = 'customer';
  end if;

  if customer.id is null then
    raise exception 'CUSTOMER_NOT_FOUND' using errcode = 'P0002';
  end if;

  return jsonb_build_object(
    'id', customer.id,
    'full_name', customer.full_name,
    'phone', customer.phone,
    'points_balance', customer.points_balance
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Atomic multi-service checkout.
-- items JSON example:
-- [{"service_slug":"detailing","quantity":1,"unit_price":2300}]
-- unit_price is optional; when omitted, the service's current price is used.
-- ---------------------------------------------------------------------------
create or replace function public.create_order(
  customer_reference text,
  items jsonb,
  payment text,
  request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  staff public.profiles%rowtype;
  customer public.profiles%rowtype;
  selected_service public.services%rowtype;
  loyalty public.loyalty_settings%rowtype;
  existing_order public.orders%rowtype;
  created_order public.orders%rowtype;
  item jsonb;
  reference text;
  item_count integer;
  item_quantity integer;
  chosen_price numeric(12,2);
  calculated_subtotal numeric(12,2) := 0;
  calculated_total numeric(12,2) := 0;
  calculated_points integer := 0;
  redeemed_points integer := 0;
  new_balance integer;
begin
  select * into staff from public.profiles where id = auth.uid();
  if staff.id is null or staff.role not in ('admin', 'worker') then
    raise exception 'STAFF_ACCESS_REQUIRED' using errcode = '42501';
  end if;

  if request_id is null then
    raise exception 'REQUEST_ID_REQUIRED' using errcode = '22023';
  end if;

  -- Serialize retries of the same client request and return the first result.
  perform pg_advisory_xact_lock(hashtextextended(request_id::text, 0));
  select * into existing_order from public.orders where client_request_id = request_id;
  if existing_order.id is not null then
    if existing_order.worker_id <> staff.id then
      raise exception 'REQUEST_ID_ALREADY_USED' using errcode = '23505';
    end if;
    select * into customer from public.profiles where id = existing_order.customer_id;
    return jsonb_build_object(
      'order_id', existing_order.id,
      'receipt_number', existing_order.receipt_number,
      'customer_id', existing_order.customer_id,
      'customer_name', customer.full_name,
      'points_balance', customer.points_balance,
      'subtotal', existing_order.subtotal,
      'total_amount', existing_order.total_amount,
      'points_added', existing_order.points_added,
      'points_redeemed', existing_order.points_redeemed,
      'payment_method', existing_order.payment_method,
      'status', existing_order.status,
      'duplicate', true
    );
  end if;

  reference := regexp_replace(trim(coalesce(customer_reference, '')), '^rio-customer:v1:', '', 'i');
  if reference ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    select * into customer from public.profiles
    where id = reference::uuid and role = 'customer' for update;
  else
    select * into customer from public.profiles
    where phone = public.normalize_phone(reference) and role = 'customer' for update;
  end if;

  if customer.id is null then
    raise exception 'CUSTOMER_NOT_FOUND' using errcode = 'P0002';
  end if;

  if jsonb_typeof(items) <> 'array' then
    raise exception 'ITEMS_MUST_BE_ARRAY' using errcode = '22023';
  end if;
  item_count := jsonb_array_length(items);
  if item_count < 1 or item_count > 20 then
    raise exception 'INVALID_ITEM_COUNT' using errcode = '22023';
  end if;
  if payment not in ('cash', 'card', 'transfer', 'points') then
    raise exception 'INVALID_PAYMENT_METHOD' using errcode = '22023';
  end if;

  select * into loyalty from public.loyalty_settings where id = 1;

  for item in select * from jsonb_array_elements(items)
  loop
    item_quantity := coalesce((item ->> 'quantity')::integer, 1);
    if item_quantity < 1 or item_quantity > 20 then
      raise exception 'INVALID_QUANTITY' using errcode = '22023';
    end if;

    select * into selected_service from public.services
    where slug = item ->> 'service_slug' and is_active = true
    for share;
    if selected_service.id is null then
      raise exception 'SERVICE_NOT_FOUND' using errcode = 'P0002';
    end if;

    chosen_price := case
      when item ? 'unit_price' and nullif(item ->> 'unit_price', '') is not null
        then (item ->> 'unit_price')::numeric(12,2)
      else selected_service.price
    end;
    if chosen_price < 0 then
      raise exception 'INVALID_PRICE' using errcode = '22023';
    end if;

    calculated_subtotal := calculated_subtotal + (selected_service.price * item_quantity);
    calculated_total := calculated_total + (chosen_price * item_quantity);
    calculated_points := calculated_points + (selected_service.points_reward * item_quantity);
  end loop;

  if payment = 'points' then
    if item_count <> 1
      or coalesce((items -> 0 ->> 'quantity')::integer, 1) <> 1
      or loyalty.reward_service_id is null
      or not exists (
        select 1 from public.services service
        where service.id = loyalty.reward_service_id
          and service.slug = items -> 0 ->> 'service_slug'
      ) then
      raise exception 'INVALID_REWARD_SERVICE' using errcode = '22023';
    end if;
    if customer.points_balance < loyalty.reward_threshold then
      raise exception 'INSUFFICIENT_POINTS' using errcode = '22003';
    end if;
    redeemed_points := loyalty.reward_threshold;
    calculated_total := 0;
    calculated_points := 0;
  end if;

  insert into public.orders (
    customer_id, worker_id, payment_method, subtotal, total_amount,
    points_added, points_redeemed, client_request_id
  ) values (
    customer.id, staff.id, payment, calculated_subtotal, calculated_total,
    calculated_points, redeemed_points, request_id
  ) returning * into created_order;

  for item in select * from jsonb_array_elements(items)
  loop
    item_quantity := coalesce((item ->> 'quantity')::integer, 1);
    select * into selected_service from public.services
    where slug = item ->> 'service_slug';
    chosen_price := case
      when payment = 'points' then 0
      when item ? 'unit_price' and nullif(item ->> 'unit_price', '') is not null
        then (item ->> 'unit_price')::numeric(12,2)
      else selected_service.price
    end;

    insert into public.order_items (
      order_id, service_id, quantity, base_unit_price, unit_price, points_reward
    ) values (
      created_order.id, selected_service.id, item_quantity, selected_service.price,
      chosen_price, case when payment = 'points' then 0 else selected_service.points_reward end
    );
  end loop;

  new_balance := customer.points_balance + calculated_points - redeemed_points;
  update public.profiles set points_balance = new_balance where id = customer.id;

  if calculated_points > 0 then
    insert into public.points_ledger (customer_id, order_id, actor_id, delta, balance_after, reason)
    values (customer.id, created_order.id, staff.id, calculated_points, customer.points_balance + calculated_points, 'earned');
  end if;
  if redeemed_points > 0 then
    insert into public.points_ledger (customer_id, order_id, actor_id, delta, balance_after, reason)
    values (customer.id, created_order.id, staff.id, -redeemed_points, new_balance, 'redeemed');
  end if;

  return jsonb_build_object(
    'order_id', created_order.id,
    'receipt_number', created_order.receipt_number,
    'customer_id', customer.id,
    'customer_name', customer.full_name,
    'points_balance', new_balance,
    'points_added', calculated_points,
    'points_redeemed', redeemed_points,
    'subtotal', calculated_subtotal,
    'total_amount', calculated_total,
    'payment_method', payment,
    'status', 'completed',
    'duplicate', false,
    'items', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', order_item.id,
        'service_id', order_item.service_id,
        'quantity', order_item.quantity,
        'base_unit_price', order_item.base_unit_price,
        'unit_price', order_item.unit_price,
        'line_total', order_item.line_total
      )), '[]'::jsonb)
      from public.order_items order_item
      where order_item.order_id = created_order.id
    )
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Admin-only cancellation. Revenue is excluded by status and loyalty changes
-- are reversed. Balance never becomes negative if earned points were spent.
-- ---------------------------------------------------------------------------
create or replace function public.cancel_order(order_id uuid, reason text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_profile public.profiles%rowtype;
  target_order public.orders%rowtype;
  customer public.profiles%rowtype;
  desired_delta integer;
  actual_delta integer;
  new_balance integer;
begin
  select * into admin_profile from public.profiles where id = auth.uid();
  if admin_profile.id is null or admin_profile.role <> 'admin' then
    raise exception 'ADMIN_ACCESS_REQUIRED' using errcode = '42501';
  end if;
  if length(trim(coalesce(reason, ''))) < 3 then
    raise exception 'CANCELLATION_REASON_REQUIRED' using errcode = '22023';
  end if;

  select * into target_order from public.orders where id = order_id for update;
  if target_order.id is null then
    raise exception 'ORDER_NOT_FOUND' using errcode = 'P0002';
  end if;
  if target_order.status = 'cancelled' then
    return jsonb_build_object('order_id', target_order.id, 'status', 'cancelled', 'duplicate', true);
  end if;

  select * into customer from public.profiles where id = target_order.customer_id for update;
  desired_delta := target_order.points_redeemed - target_order.points_added;
  new_balance := greatest(0, customer.points_balance + desired_delta);
  actual_delta := new_balance - customer.points_balance;

  update public.profiles set points_balance = new_balance where id = customer.id;
  update public.orders set
    status = 'cancelled',
    cancelled_at = now(),
    cancelled_by = admin_profile.id,
    cancellation_reason = trim(reason),
    updated_at = now()
  where id = target_order.id;

  if actual_delta <> 0 then
    insert into public.points_ledger (customer_id, order_id, actor_id, delta, balance_after, reason, note)
    values (customer.id, target_order.id, admin_profile.id, actual_delta, new_balance, 'reversal', trim(reason));
  end if;

  return jsonb_build_object(
    'order_id', target_order.id,
    'status', 'cancelled',
    'points_delta', actual_delta,
    'points_balance', new_balance,
    'duplicate', false
  );
end;
$$;

-- Manual point adjustments remain auditable and admin-only.
create or replace function public.adjust_customer_points(
  customer_id uuid,
  points_delta integer,
  note text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_profile public.profiles%rowtype;
  customer public.profiles%rowtype;
  new_balance integer;
begin
  select * into admin_profile from public.profiles where id = auth.uid();
  if admin_profile.id is null or admin_profile.role <> 'admin' then
    raise exception 'ADMIN_ACCESS_REQUIRED' using errcode = '42501';
  end if;
  if points_delta = 0 or length(trim(coalesce(note, ''))) < 3 then
    raise exception 'DELTA_AND_NOTE_REQUIRED' using errcode = '22023';
  end if;

  select * into customer from public.profiles where id = customer_id and role = 'customer' for update;
  if customer.id is null then
    raise exception 'CUSTOMER_NOT_FOUND' using errcode = 'P0002';
  end if;
  new_balance := customer.points_balance + points_delta;
  if new_balance < 0 then
    raise exception 'INSUFFICIENT_POINTS' using errcode = '22003';
  end if;

  update public.profiles set points_balance = new_balance where id = customer.id;
  insert into public.points_ledger (customer_id, actor_id, delta, balance_after, reason, note)
  values (customer.id, admin_profile.id, points_delta, new_balance, 'admin_adjustment', trim(note));

  return jsonb_build_object('customer_id', customer.id, 'points_balance', new_balance);
end;
$$;

revoke all on function public.resolve_customer(text) from public;
revoke all on function public.create_order(text, jsonb, text, uuid) from public;
revoke all on function public.cancel_order(uuid, text) from public;
revoke all on function public.adjust_customer_points(uuid, integer, text) from public;

grant execute on function public.resolve_customer(text) to authenticated;
grant execute on function public.create_order(text, jsonb, text, uuid) to authenticated;
grant execute on function public.cancel_order(uuid, text) to authenticated;
grant execute on function public.adjust_customer_points(uuid, integer, text) to authenticated;
